apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleeper
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      parallelism: 2
      completions: 6
      template:
        spec:
          containers:
          - name: sleeper
            image: ubuntu:24.04
            command: ["sh", "-c","echo 'this app running && sleep'; sleep 10"]
          restartPolicy: Never