apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gk-13-pvc
  namespace: gk-13-ns
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
