apiVersion: v1
metadata:
  name: gk-14-cm
  namespace: gk-14-ns
data:
  index.html: |2-
     <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Hello!</title>
        </head>
        <body>
          <p>Hello World!</p>
        </body>
kind: ConfigMap


# kubectl create configmap gk-14-cm \
# --from-file=index.html \  
# -n gk-14-ns \ 
# --dry-run=client \ 
# -o yaml > cm.nginx.index.html.yaml