apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gk-14-pod-sts
  namespace: gk-14-ns
spec:
  replicas: 3
  minReadySeconds: 5
  updateStrategy:
    type: RollingUpdate    
  serviceName: gk-14-svc
  selector:
    matchLabels:
      app: gk-14-pod-sts
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 128Mi
  template:
    metadata:
      labels:
        app: gk-14-pod-sts
    spec:
      terminationGracePeriodSeconds: 1
      volumes:
        - name: nginx-init
          configMap:
            name: gk-14-cm   

      initContainers:
      - name: nginx-init
        image: ubuntu:22.04
        command: ['sh', '-c', 'cp -rL /data/* /usr/share/nginx/html']
        volumeMounts:
        - name: nginx-init
          mountPath: /data
        - name: www
          mountPath: /usr/share/nginx/html

      containers:
      - name: gk-14-nginx
        image: nginx:1.25.2
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html


# kubectl run test-dns -n gk-14-ns --image=busybox:1.36 -it --rm --restart=Never -- sh

# ╰─ kubectl delete pods -n gk-14-ns gk-14-pod-sts-1