apiVersion: v1
kind: Service
metadata:
  labels:
    app: gk-14-pod-sts
  name: gk-14-svc
  namespace: gk-14-ns
spec:
  clusterIP: None
  selector:
    app: gk-14-pod-sts
  type: ClusterIP
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80

