apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: gk-09-api
  labels:
    name: curl-test
spec:
  containers:
  - name: curl-test
    image: quay.io/curl/curl:8.16.0
    resources:      
    ports:
      - containerPort: 80
