apiVersion: v1
kind: Service
metadata:
  name: gk-svc
  namespace: gk-09-ns
spec:
  type: ClusterIP
  selector:
    tier: gk-api
    company: gk-entertainment   
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
