apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gk-web
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@gitlab.com:geloke59/argocd.git
    targetRevision: master
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: ns-gk-22