apiVersion: v1
kind: Service
metadata:
  name: {{printf "%s-%s" (include "gk-web.fullname" .) .Values.podLabels.environment }}
  labels: {{- include "gk-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.tls.enabled }}  
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector: {{- include "gk-web.selectorLabels" . | nindent 4 }}
