apiVersion: v1
kind: ConfigMap
metadata:
  name: {{printf "%s-%s" (include "gk-web.fullname" .) .Values.podLabels.environment }}-web-content
  labels:
    {{- include "gk-web.labels" . | nindent 4 }}

data:
  index.html: |
    <!DOCTYPE html>
    <html lang="pl">
      <head>
        <meta charset="UTF-8">
        <title>{{ .Values.web.title }}</title>
      </head>
      <body>
        <h1>{{ .Values.web.title }}</h1>
        <p>{{ .Values.web.message }}</p>
        <p>Release: {{ .Release.Name }}</p>
        <p>Chart: {{ .Chart.Name }}-{{ .Chart.Version }}</p>
      </body>
    </html>