apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - deny.ingress.backend.yaml
  - allow.ingress.frontend.backend.yaml  
  - deny.egress.backend.yaml
  - allow.egress.backend.dns.yaml
  - allow.egress.backend.database.yaml
  - deny.ingress.database.yaml
  - allow.ingress.backend.database.yaml