apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: gk-21-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:v1.27
          ports:
            - name: smtp
              containerPort: 1025
            - name: web
              containerPort: 8025
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: gk-21-app
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
    - name: web
      port: 8025
      targetPort: web