apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: metrics-lab-app
  namespace: gk-21-app
  labels:
    release: monitoring
spec:
  groups:
    - name: metrics-lab-app.rules
      rules:
        - alert: MetricsLabAppHighErrorRate
          expr: |
            (
              sum(
                rate(
                  lab_http_requests_total{
                    job="metrics-lab-app",
                    status=~"5.."
                  }[5m]
                )
              )
              /
              sum(
                rate(
                  lab_http_requests_total{
                    job="metrics-lab-app"
                  }[5m]
                )
              )
            ) * 100 > 20
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High error rate in metrics-lab-app"
            description: "Error rate has exceeded 20% for more than 1 minute."