apiVersion: v1
kind: Namespace
metadata:
  name:  gk-12-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gk-12-rq
  namespace: gk-12-ns
spec:
  hard:
    cpu: "1000m"
    limits.cpu: "2500m"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: gk-12-lr
  namespace: gk-12-ns
spec:
  limits:
  - type: Container
    default:
      cpu: "150m"
    max:
      cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gk-12-pod
  namespace: gk-12-ns
spec:
  selector:
    matchLabels:
      app: gk-12-pod
      tier: php-apache
  template:
    metadata:
      labels:
        app: gk-12-pod
        tier: php-apache
    spec:
      containers:
      - name: php-apache-container
        image: registry.k8s.io/hpa-example
        resources:          
          requests:
            cpu: "100m"
          limits:
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gk-12-svc
  namespace: gk-12-ns
spec:
  selector:
    app: gk-12-pod
    tier: php-apache
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gk-12-hpa
  namespace: gk-12-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gk-12-pod
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60



  