---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-backend
  namespace: gpu
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      workload: gpu-backend
  template:
    metadata:
      labels:
        workload: gpu-backend
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
      terminationGracePeriodSeconds: 1
      initContainers:
      - name: node-checker
        image: ubuntu:24.04
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
        - "/bin/bash"
        - "-c"
        # We know that isa-lab-cluster-worker2 has GPUs ;)
        # Note that this is not a real-world check, it's just for this exercise.
        # You should (almost) never do a check using the node name.
        args:
        - >
          test "${NODE_NAME}" = "isa-lab-cluster-worker2"
      containers:
      - name: sleeper 
        image: ubuntu:24.04
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        command: # This container needs GPUs to sleep more efficiently!
        - "sleep"
        - "infinity"